### PR TITLE
Update version and release activity

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Did not find this activity on http://activities.sugarlabs.org/en-US/sugar/ but http://activities.sugarlabs.org/activities/4625/ confirms that v5 was the last released version of this activity. @quozl  Please tell me how can I add this activity to http://activities.sugarlabs.org

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed to 04f440c.

Did find this activity on http://activities.sugarlabs.org/en-US/sugar/ by searchings for *abcs*.

Did find this activity on http://translate.sugarlabs.org/ and saw updates, so added a commit, but because you used your *master* branch or your repository was protected, I was unable to push, so I took your commits here and added my own and pushed to this repository *master*.

* https://github.com/sugarlabs/iknowmyabcs/commit/d6130966f8ea1a355a53e59686954b5cce598ccd new translations,
* https://github.com/sugarlabs/iknowmyabcs/commit/e343f8ec56da046f7547549998cd95515bbe55b5 your f2038c1 with changed commit message,
* https://github.com/sugarlabs/iknowmyabcs/commit/8347e8a3e538cb893519bdaeee627eb61cd675b9 your 04f440c unchanged.

To add to http://activities.sugarlabs.org register your account, give me your account username, and I'll add you as a maintainer of I Know My ABCs.  Then you'll be able to complete the rest of the [checklist](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer).

**Comment by yell0wfl4sh** [comment]
thanks.
username: yashagrawal
email: yagrawal900@gmail.com

**Comment by quozl** [comment]
You have been added as a developer of I Know My ABCs activity.  You may need to reload a page if it was open while I did that.  You should now have the upload feature available.

**Comment by quozl** [comment]
Looks like these commits are on the master branch already.

**Pull request closed without merging**
