### PR TITLE
Fixing files for deployment of ASLOv3

### PR DESCRIPTION
**Pull request by vipulgupta2048**
In reference to the project in GSoC 2018,
For the successful deployment of ASLOv3, some files and activity.info need to be added/fixed/updated to present correct metadata on the website.

Updated Parameters:-
1. `website`
2. `repository`
3. `summary`
4. Changed `category` to `tags`

Please review the same, and suggest any changes that are required.

### CODE REVIEW

**Comment by quozl** [comment]
Missing newline at end of file.

And I'll quibble at your justification; _successful deployment of ASLOv3_ could also be achieved by using the GitHub API to correlate _bundle_id_ against a repository, and by finding the bundle in the Help Activity helplink.json file.

**Comment by vipulgupta2048** [comment]
@quozl I do agree with your criticism, but my project was about getting the repositories back in shape so that the deployment could be easier. I really do agree with your method of GitHub API and I have been working on this in the weekend and will be making a PR soon. Thanks for helping me out.  

Hence I think we can work on both sides by fixing some activities every week as they are migrated (Adding metadata, screenshots) and also making ASLO accept default values and testing it out. (like you stated earlier) Hence, make good progress on deploying ASLOv3.
How about that? But I do want a set approach on my project. As I am bit unsure of what path are we following. I do apologize, for the confusion in mind.

**Comment by quozl** [comment]
Thanks.  Just no need for justification in pull request comment; the metadata needs changing anyway.  Will you be fixing the missing newline?

**Comment by vipulgupta2048** [comment]
I am happy that we are on the same page. :see_no_evil: 
Changes requested has been implemented.

**Comment by quozl** [comment]
Mysterious trailing slash; why?  See https://github.com/sugarlabs/iknowmyabcs/pull/10/commits/52cd5e9dc85c7417edd1a328dd2096079cd37785

**Comment by vipulgupta2048** [comment]
Fixed @quozl. Ready to merge

**Pull request merged**
