### PR TITLE
Fix audio bug and port setup.py to gtk3

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
@quozl  please review!

### CODE REVIEW

**Comment by yell0wfl4sh** [comment]
WIP: fixing #6

**Comment by quozl** [comment]
Reviewed to c967825.  Is there extra code in setup.py that isn't needed?  It looks like it was copied from Turtle Art.

**Comment by yell0wfl4sh** [comment]
Indeed there was, added a commit fixing it.

**Comment by yell0wfl4sh** [comment]
Fixed #6 
@quozl  please see!

**Comment by quozl** [comment]
@yashagrawal3, I'm a bit confused; you seem to have removed all calls to playing audio, as well as fix the audio playing module.  Which did you intend?

**Comment by yell0wfl4sh** [comment]
-@quozl , That was extra code, it was used for smile/frown feedback audio for any other activity and this activity has no such thing, so I removed it. ```play_target_audio()``` is doing the work of playing target audio here.

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Pull request merged**
